### ISSUE TITLE
Change absolute filepaths to relative filepaths

### ISSUE THREAD

**Issue by mebeZ** [mebeZ/4156-Team-Project#1]
There shouldn't be any absolute filepaths (i.e. those starting with '/') in the codebase. I originally did absolute paths because for some reason the relative filepaths were not working. However, absolute filepaths makes the code work only on my machine and not other peoples.

Once you change the absolute paths into relative paths, make sure that the code runs successfully. To check this, go to RestService.java and run FaceController.getEyeColor("sarah"). This should output 'blue' in the logs.

To understand the difference between an absolute and a relative filepath, please read this article: https://www.geeksforgeeks.org/absolute-relative-pathnames-unix/

**Comment by YonghanXie** [comment]
Simple copy the relative path in IDE should make this works.
